apiVersion: v1
kind: Service
metadata:
  name: cicd-demo-service
  namespace: default
spec:
  selector:
    app: cicd-demo-app
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
    nodePort: 30080   # Access via http://<Worker-IP>:30080